services:
  proxy:
    image: rancher/nginx-ingress-controller:v1.12.1-hardened3
    container_name: nginx-proxy
    hostname: nginx-proxy
    entrypoint:
      - /docker-entrypoint.sh
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/hooks:/docker-entrypoint.d/
    links:
      - default

  default:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: dev
        COMMIT: xxx
    image: echoback:dev
    container_name: echo-back
    hostname: echo-back
    volumes:
      - ./src/files:/files
    environment:
      DEBUG: true
      TEMPLATE_HTML: 'files/simple.html'
    expose:
      - 3000
    ports:
      - 3000:3000
